// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmm-gzlmjJTRAPNHs10EnYo2iMMpHq4ko',
    appId: '1:830993798432:web:bdf4dc07cf0f60805a7345',
    messagingSenderId: '830993798432',
    projectId: 'medication-reminder-90690',
    authDomain: 'medication-reminder-90690.firebaseapp.com',
    storageBucket: 'medication-reminder-90690.firebasestorage.app',
    measurementId: 'G-TVT3XWBEQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCiMHUshqrv9wZwKjcL5yHRwvZ--V-LjY',
    appId: '1:830993798432:android:a57588292b0512a45a7345',
    messagingSenderId: '830993798432',
    projectId: 'medication-reminder-90690',
    storageBucket: 'medication-reminder-90690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV3lg5G9CKRAHCPsL5T7xL8awGctU7rnw',
    appId: '1:830993798432:ios:a5a79ddca3236ce95a7345',
    messagingSenderId: '830993798432',
    projectId: 'medication-reminder-90690',
    storageBucket: 'medication-reminder-90690.firebasestorage.app',
    iosBundleId: 'com.phongtruong.medicationreminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV3lg5G9CKRAHCPsL5T7xL8awGctU7rnw',
    appId: '1:830993798432:ios:ef77245642c0c49a5a7345',
    messagingSenderId: '830993798432',
    projectId: 'medication-reminder-90690',
    storageBucket: 'medication-reminder-90690.firebasestorage.app',
    iosBundleId: 'com.duytruong.medicationreminder.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmm-gzlmjJTRAPNHs10EnYo2iMMpHq4ko',
    appId: '1:830993798432:web:605391c5f227cd625a7345',
    messagingSenderId: '830993798432',
    projectId: 'medication-reminder-90690',
    authDomain: 'medication-reminder-90690.firebaseapp.com',
    storageBucket: 'medication-reminder-90690.firebasestorage.app',
    measurementId: 'G-4YE5VR06ZK',
  );
}
